---
version: '2'
services:

  postgres:
    image: postgres:10.3-alpine

    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: postgresdb

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'telegram_bot'

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d